// https://nuxt.com/docs/api/configuration/nuxt-config
import type { NuxtConfig } from "nuxt/schema";
import { nodeResolve } from "@rollup/plugin-node-resolve";
import tailwindcss from "@tailwindcss/vite";
import { dirname, join } from "node:path";

// The SDK's browser XML parser needs DOMParser, which Workers don't have, so reading R2 listings failed in production.
// Its other parser is plain JavaScript and runs anywhere.
const awsXmlParser = {
  name: "aws-xml-parser",
  resolveId(source: string, importer?: string) {
    if (source === "./xml-parser" && importer?.includes("/@aws-sdk/xml-builder/")) return join(dirname(importer), "xml-parser.js");
  },
};

export default {
  compatibilityDate: "2025-10-01",
  nitro: {
    preset: "cloudflare_module",
    // Link preview images are drawn by Takumi's WebAssembly build (server/utils/galleryCard.ts)
    experimental: { wasm: true },
    hooks: {
      "rollup:before": (nitro, config) => {
        if (nitro.options.dev || !Array.isArray(config.plugins)) return;
        // Workers need the SDK's browser runtime, including its package.json browser mappings.
        config.plugins = [awsXmlParser, ...config.plugins].map((plugin) =>
          plugin && typeof plugin === "object" && "name" in plugin && plugin.name === "node-resolve"
            ? nodeResolve({
                browser: true,
                mainFields: ["browser", "module", "main"],
                exportConditions: nitro.options.exportConditions,
                preferBuiltins: false,
                rootDir: nitro.options.rootDir,
                modulePaths: nitro.options.nodeModulesDirs,
              })
            : plugin,
        );
      },
    },
    cloudflare: {
      deployConfig: true,
      nodeCompat: true,
    },
  },
  routeRules: {
    "/admin": { headers: { "cache-control": "private, no-store" } },
    "/admin/**": { headers: { "cache-control": "private, no-store" } },
    // Galleries were called collections before; keep old dashboard links working
    "/admin/collections/**": { redirect: "/admin/galleries/**" },
    "/api/admin/**": { headers: { "cache-control": "private, no-store" } },
    "/api/auth/**": { headers: { "cache-control": "private, no-store" } },
  },
  // Icons are generated by design/brand/generate.py
  app: {
    head: {
      link: [
        // sizes="32x32" keeps Chrome from preferring the .ico over the SVG
        { rel: "icon", href: "/favicon.ico", sizes: "32x32" },
        { rel: "icon", href: "/icon.svg", type: "image/svg+xml" },
        { rel: "apple-touch-icon", href: "/apple-touch-icon.png" },
        { rel: "manifest", href: "/manifest.webmanifest" },
      ],
      meta: [
        { name: "theme-color", content: "#FFD21F" },
        // iOS otherwise uses the page title as the home screen label
        { name: "apple-mobile-web-app-title", content: "FindPhotosOfMe" },
      ],
    },
  },
  devtools: { enabled: false },
  modules: ["shadcn-nuxt", "convex-nuxt"],
  css: ["~/assets/css/tailwind.css"],
  devServer: {
    port: 3001,
  },
  convex: {
    url: process.env.NUXT_PUBLIC_CONVEX_URL,
  },
  runtimeConfig: {
    serviceToken: "",
    pythonApiUrl: "",
    r2AccountId: "",
    r2BucketName: "",
    r2AccessKeyId: "",
    r2SecretAccessKey: "",
    // Only tests set this, to point at their fake R2; otherwise the account's R2 endpoint is used.
    r2Endpoint: "",
    public: {
      origin: "",
      convexUrl: "",
      convexSiteUrl: "",
      // Set NUXT_PUBLIC_PAYMENTS=true once Lemon Squeezy is live; until then Top up says top-ups open soon.
      payments: false,
    },
  },
  vite: {
    plugins: [tailwindcss()],
  },
  shadcn: {
    prefix: "",
    componentDir: "./app/components/ui",
  },
} satisfies NuxtConfig;
